# Change these first
owner: Koen-HowtoHack # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: How to Hack
    url: https://www.howtohack.nl/
  - name: Statuspagina How to Hack & Codeblocks
    url: https://status.howtohack.nl/
  - name: Codeblocks
    url: https://www.codeblocks.nl/
  - name: Codeblocks CDN
    url: https://cdn.codeblocks.nl/
  - name: Codeblocks Docs
    url: https://docs.codeblocks.nl/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.howtohack.nl
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: How to Hack
  introTitle: "Welkom op de status pagina van **How to Hack**"
  introMessage: Op deze pagina vind je de statussen van **How to Hack** en **Codeblocks**.
  navbar:
    - title: Status
      href: /
    - title: How to Hack
      href: https://www.howtohack.nl
    - title: Codeblocks
      href: https://www.codeblocks.nl

i18n: 
      activeIncidents: Lopende incidenten
      allSystemsOperational: Alle system zijn operationeel!
      incidentReport: "Incident #$NUMBER melding →"
      activeIncidentSummary: Gestart op $DATE met $POSTS bericht(en).
      incidentTitle: Incident $NUMBER details
      incidentDetails: Incident details
      incidentFixed: Opgelost
      incidentOngoing: Lopend
      incidentOpenedAt: Geopend op
      incidentClosedAt: Closed at
      incidentViewOnGitHub: Bekijk en abboneer via Github
      incidentCommentSummary: Posted at $DATE by $AUTHOR
      incidentBack: ← Back to all incidents
      pastIncidents: Past Incidents
      pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
      liveStatus: Live Status
      overallUptime: "Overall uptime: $UPTIME"
      overallUptimeTitle: Overall uptime
      averageResponseTime: "Average response time: $TIMEms"
      averageResponseTimeTitle: Average response
      sevelDayResponseTime: 7-day response time
      responseTimeMs: Response time (ms)
      up: Up
      down: Down
      degraded: Degraded
      ms: ms
      loading: Loading
      navGitHub: GitHub
      footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
      rateLimitExceededTitle: Rate limit exceeded
      rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
      rateLimitExceededWhatDoesErrorMean: What does this error mean?
      rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
      rateLimitExceededErrorHowCanFix: How can I fix it?
      rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
      rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
      rateLimitExceededHasSet: You have a personal access token set.
      rateLimitExceededRemoveToken: Remove token
      rateLimitExceededGitHubPAT: GitHub Personal Access Token
      rateLimitExceededCopyPastePAT: Copy and paste your token
      rateLimitExceededSaveToken: Save token
      errorTitle: An error occurred
      errorIntro: An error occurred in trying to get the latest status details.
      errorText: You can try again in a few moments.
      errorHome: Go to the homepage
      pastScheduledMaintenance: Past Scheduled Maintenance
      scheduledMaintenance: Scheduled Maintenance
      scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
      scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
      startedAt: Begonnen op
      startsAt: Begint op
      duration: Duur
      durationMin: $DURATION minuten
      incidentCompleted: Afgerond
      incidentScheduled: Gepland
      duration24H: 24 uur
      duration7D: 7 dagen
      duration30D: 30 dagen
      duration1Y: 1 jaar
      durationAll: all
      locale: nl-NL
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
